services:
  rpi-monitor:
    build: .
    container_name: rpi-monitor
    restart: unless-stopped
    pid: host
    network_mode: host
    volumes:
      - /sys:/sys:ro
      - /etc/hostname:/etc/hostname:ro
