services:
  rpi-monitor:
    build: .
    container_name: rpi-monitor
    restart: unless-stopped
    pid: host
    ports:
      - "5000:5000"
    volumes:
      - /sys:/sys:ro
      - /etc/hostname:/etc/hostname:ro
